trigger: none
pool:
  name: Hosted VS2017
variables:
  APIFolder: 'MMA.WebApi'
  AzureFunctionsFolder: 'MMA.Azure.Functions'
  BuildConfiguration: 'UAT'

steps:
- task: UseDotNet@2
  displayName: "Install .NET core SDK 3.1.x"
  inputs:
    packageType: sdk
    version: 3.1.x

- task: DotNetCoreCLI@2  
  displayName: 'Restore dependencies'  
  inputs:        
    command: "restore"
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: 'Build API - $(BuildConfiguration)'
  inputs:    
    command: "build"
    arguments: "--configuration $(BuildConfiguration)"      
    projects: '$(APIFolder)/**/*.csproj'


- task: DotNetCoreCLI@2
  displayName: 'Publish API - $(BuildConfiguration)'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    projects: '**/$(SolutionFolder)/**/*.sln'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(APIFolder)/Reports'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/$(APIFolder)/Reports'

- task: DotNetCoreCLI@2
  displayName: 'Build Azure Functions - $(BuildConfiguration)'
  inputs:    
    command: "build"
    arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"
    projects: '$(AzureFunctionsFolder)/**/*.csproj'
    zipAfterPublish: true
    modifyOutputPath: true
  

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts - $(BuildConfiguration)'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'dist'
    parallel: true
    parallelCount: 4